---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  # Each SITE_ID is a different zone
  topology.kubernetes.io/zone: ran-cu-devanahalli60-server-profile-cu-dell-r640-00

resources:
  # SRIOV Configs
  - 00-mcp-wait-job-devanahalli60-r13dell6-sriov.yaml
  - 01-devanahalli60-sriov-namespace.yaml
  - 02-devanahalli60-sriov-node-policies.yaml
  - 03-devanahalli60-sriov-networks.yaml
  - 04-devanahalli60-local-storage-{worker_node.value.config_context.server_profile_name}}.yaml"
  - 05-devanahalli60-storageclass-{worker_node.value.config_context.server_profile_name}}.yaml"
 
