global:
  # ems ip address
  emsIp: "2001:100:252::19a:10:10"

  # ne information
  namespace: "cnf"
  neType: "acpf"
  neId: "20000"
  flavorId: "tiny-enterprise-poc"
  podGroupPolicy: "cmp0#1-dmp0#1-pmp0#1-cpp0#1-csp0#1-cip0#1-ctp0#1"

  # continaer image & policy
  images:
    repository: "SSBastion.comm.ibm.gsc:5000"
    pullPolicy: "IfNotPresent"
    pullSecrets: "UNUSED"
    cmp: "rel-ran/vzw-acpf-cmp:SVR21ACPCVZWI32_R00"
    dmp: "rel-ran/vzw-acpf-dmp:SVR21ACPCVZWI32_R00"
    pmp: "rel-ran/vzw-acpf-pmp:SVR21ACPCVZWI32_R00"
    cpp: "rel-ran/vzw-acpf-cpp:SVR21ACPCVZWI32_R00"
    csp: "rel-ran/vzw-acpf-csp:SVR21ACPCVZWI32_R00"
    cip: "rel-ran/vzw-acpf-cip:SVR21ACPCVZWI32_R00"
    ctp: "rel-ran/vzw-acpf-ctp:SVR21ACPCVZWI32_R00"

  nodeport:
    netconf: "31510"

  # service account to acess the API server. This has a default value if not set.
  serviceAccountName: "" # "default: vran-serviceaccount"
  
csp:
  # network attachment definition for sriov
  sriov:
    bh0:
#      resource: "openshift.io/sriov_ext0" # sriov 생성 시 작성했던 resourceName을 적는다
      resource: "openshift.io/cu_sriov_vfs_ens1f0"
      vlan: "2006"
      mtu: "1500"
      cidr: "2001:db8:b00:2006::/64"
      gw: "2001:db8:b00:2006::1"
      addr: "2001:db8:b00:2006::11:11"
