---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  # Each SITE_ID is a different zone
  topology.kubernetes.io/zone: ran-cu-devanahalli60-server-profile-cu-dell-r640-00

commonAnnotations:
  argocd.argoproj.io/sync-options: Prune=false
  argocd.argoproj.io/compare-options: IgnoreExtraneous  


resources:
  - 00-label-wait-job-devanahalli60-r13dell6-mc.yaml

  - 00-mcp-wait-job-devanahalli60-r13dell6-mc.yaml  
  - 01-mc-lvm-ran-cu-devanahalli60-server-profile-cu-dell-r640-00.yaml