---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  # Each SITE_ID is a different zone
  topology.kubernetes.io/zone: ran-cu-devanahalli60-server-profile-cu-dell-r640-00

resources:
  # SRIOV Configs
  - 00-hook-mcp-wait-job-devanahalli60.yaml
  - 00-devanahalli60-sriov-namespace.yaml
  - 00-devanahalli60-sriov-node-policy.yaml
  - 01-devanahalli60-sriov-networks.yaml
