---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  # Each SITE_ID is a different zone
  topology.kubernetes.io/zone: ran-cu-devanahalli60-server-profile-cu-dell-r640-00

commonAnnotations:  
#  argocd.argoproj.io/sync-wave: "10"
  argocd.argoproj.io/sync-options: Prune=false
  argocd.argoproj.io/compare-options: IgnoreExtraneous  


resources:
  - 00-hook-sno-5-wait-job-devanahalli60.yaml

  - 00-hook-paoperator-wait-job-devanahalli60.yaml
  - 00-mcp-ran-cu-devanahalli60-server-profile-cu-dell-r640-00.yaml
  - 01-pao-ran-cu-devanahalli60-server-profile-cu-dell-r640-00-pao-profile-cu-dell-r640-00.yaml
#  - 00-node-labels.yaml
#  - 01-mcp-wait-job-sa-role.yaml
